baseURL: https://mathup.org/
title: MathUp
languageCode: en
defaultContentLanguage: en
paginate: 5
theme: github.com/adityatelange/hugo-PaperMod

module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod
  hugoVersion:
    min: '0.89.2'

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  # minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  category: categories
  tag: tags
  module: modules

markup:
  goldmark:
    renderer:
      unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: false
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
