description: 'Semantic markup for symbolic mathematics'
author: Me

defaultTheme: auto
# disableThemeToggle: true
ShowShareButtons: true
ShowReadingTime: true
# disableSpecial1stPost: true
displayFullLangName: true
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: true
ShowToc: true
# comments: false
images: ['papermod-cover.png']

profileMode:
  enabled: false
  title: MathUp
  imageUrl: '#'
  imageTitle: my image
  # imageWidth: 120
  # imageHeight: 120
  buttons:
    - name: Archives
      url: archives
    - name: Tags
      url: tags

socialIcons:
  - name: github
    url: 'https://github.com/mathup'
  - name: RsS
    url: 'index.xml'

editPost:
  URL: 'https://github.com/mathup/mathup.org/tree/main/content'
  Text: 'Suggest Changes' # edit text
  appendFilePath: true # to append file path to Edit link

# label:
#     text: "Home"
#     icon: icon.png
#     iconHeight: 35

# analytics:
#     google:
#         SiteVerificationTag: "XYZabc"

# assets:
#     favicon: "<link / abs url>"
#     favicon16x16: "<link / abs url>"
#     favicon32x32: "<link / abs url>"
#     apple_touch_icon: "<link / abs url>"
#     safari_pinned_tab: "<link / abs url>"

# cover:
#     hidden: true # hide everywhere but not in structured data
#     hiddenInList: true # hide on list pages and home
#     hiddenInSingle: true # hide on single page

# fuseOpts:
#     isCaseSensitive: false
#     shouldSort: true
#     location: 0
#     distance: 1000
#     threshold: 0.4
#     minMatchCharLength: 0
#     keys: ["title", "permalink", "summary", "content"]
